#!/usr/bin/env ruby
# frozen_string_literal: true

require 'thor'
require 'colorize'

module OrsumInflandi
  module CLI
    class App < Thor
      package_name 'orsum-inflandi'

      desc 'start', 'Start the app or a part of it'
      option :backend, type: :boolean, default: true
      option :frontend, type: :boolean, default: true
      option :force_build, type: :boolean
      option :dev, type: :boolean, default: false
      option :dual_frontend, type: :boolean, default: false

      def start
        require_relative 'commands/start'
        Commands::Start.new(options.dup).run
      end

      desc 'mock', 'Start a dummy mock server to test frontend'
      option :port, type: :numeric, default: 4560

      def mock
        require_relative 'commands/mock'

        Commands::Mock.new(options.dup).run
      end
    end
  end
end

OrsumInflandi::CLI::App.start(ARGV)
