# frozen_string_literal: true

source 'https://rubygems.org'
ruby '2.6.3'

gem 'colorize'
gem 'google-protobuf'
gem 'rubocop'
gem 'rubocop-performance'
gem 'sorbet', group: :development
gem 'sorbet-runtime'
gem 'thor'
