// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/Types.proto

package Types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GameType int32

const (
	GameType_FOUR_IN_A_ROW GameType = 0
)

var GameType_name = map[int32]string{
	0: "FOUR_IN_A_ROW",
}

var GameType_value = map[string]int32{
	"FOUR_IN_A_ROW": 0,
}

func (x GameType) String() string {
	return proto.EnumName(GameType_name, int32(x))
}

func (GameType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_83b407dd639a41e8, []int{0}
}

type ChatMessageContext int32

const (
	ChatMessageContext_LOBBY   ChatMessageContext = 0
	ChatMessageContext_IN_GAME ChatMessageContext = 1
)

var ChatMessageContext_name = map[int32]string{
	0: "LOBBY",
	1: "IN_GAME",
}

var ChatMessageContext_value = map[string]int32{
	"LOBBY":   0,
	"IN_GAME": 1,
}

func (x ChatMessageContext) String() string {
	return proto.EnumName(ChatMessageContext_name, int32(x))
}

func (ChatMessageContext) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_83b407dd639a41e8, []int{1}
}

type GameResult int32

const (
	GameResult_WON  GameResult = 0
	GameResult_LOST GameResult = 1
	GameResult_TIE  GameResult = 2
)

var GameResult_name = map[int32]string{
	0: "WON",
	1: "LOST",
	2: "TIE",
}

var GameResult_value = map[string]int32{
	"WON":  0,
	"LOST": 1,
	"TIE":  2,
}

func (x GameResult) String() string {
	return proto.EnumName(GameResult_name, int32(x))
}

func (GameResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_83b407dd639a41e8, []int{2}
}

type GameRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 GameType `protobuf:"varint,2,opt,name=type,proto3,enum=GameType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameRequest) Reset()         { *m = GameRequest{} }
func (m *GameRequest) String() string { return proto.CompactTextString(m) }
func (*GameRequest) ProtoMessage()    {}
func (*GameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_83b407dd639a41e8, []int{0}
}

func (m *GameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameRequest.Unmarshal(m, b)
}
func (m *GameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameRequest.Marshal(b, m, deterministic)
}
func (m *GameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameRequest.Merge(m, src)
}
func (m *GameRequest) XXX_Size() int {
	return xxx_messageInfo_GameRequest.Size(m)
}
func (m *GameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GameRequest proto.InternalMessageInfo

func (m *GameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GameRequest) GetType() GameType {
	if m != nil {
		return m.Type
	}
	return GameType_FOUR_IN_A_ROW
}

type User struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_83b407dd639a41e8, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Game struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 GameType `protobuf:"varint,2,opt,name=type,proto3,enum=GameType" json:"type,omitempty"`
	Id                   uint32   `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Initiator            *User    `protobuf:"bytes,4,opt,name=initiator,proto3" json:"initiator,omitempty"`
	Opponent             *User    `protobuf:"bytes,5,opt,name=opponent,proto3" json:"opponent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game) Reset()         { *m = Game{} }
func (m *Game) String() string { return proto.CompactTextString(m) }
func (*Game) ProtoMessage()    {}
func (*Game) Descriptor() ([]byte, []int) {
	return fileDescriptor_83b407dd639a41e8, []int{2}
}

func (m *Game) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game.Unmarshal(m, b)
}
func (m *Game) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game.Marshal(b, m, deterministic)
}
func (m *Game) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game.Merge(m, src)
}
func (m *Game) XXX_Size() int {
	return xxx_messageInfo_Game.Size(m)
}
func (m *Game) XXX_DiscardUnknown() {
	xxx_messageInfo_Game.DiscardUnknown(m)
}

var xxx_messageInfo_Game proto.InternalMessageInfo

func (m *Game) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Game) GetType() GameType {
	if m != nil {
		return m.Type
	}
	return GameType_FOUR_IN_A_ROW
}

func (m *Game) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Game) GetInitiator() *User {
	if m != nil {
		return m.Initiator
	}
	return nil
}

func (m *Game) GetOpponent() *User {
	if m != nil {
		return m.Opponent
	}
	return nil
}

type GameList struct {
	Games                []*Game  `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameList) Reset()         { *m = GameList{} }
func (m *GameList) String() string { return proto.CompactTextString(m) }
func (*GameList) ProtoMessage()    {}
func (*GameList) Descriptor() ([]byte, []int) {
	return fileDescriptor_83b407dd639a41e8, []int{3}
}

func (m *GameList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameList.Unmarshal(m, b)
}
func (m *GameList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameList.Marshal(b, m, deterministic)
}
func (m *GameList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameList.Merge(m, src)
}
func (m *GameList) XXX_Size() int {
	return xxx_messageInfo_GameList.Size(m)
}
func (m *GameList) XXX_DiscardUnknown() {
	xxx_messageInfo_GameList.DiscardUnknown(m)
}

var xxx_messageInfo_GameList proto.InternalMessageInfo

func (m *GameList) GetGames() []*Game {
	if m != nil {
		return m.Games
	}
	return nil
}

type FourInARowTurnPayload struct {
	GameID               uint32   `protobuf:"varint,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
	Row                  uint32   `protobuf:"varint,2,opt,name=row,proto3" json:"row,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FourInARowTurnPayload) Reset()         { *m = FourInARowTurnPayload{} }
func (m *FourInARowTurnPayload) String() string { return proto.CompactTextString(m) }
func (*FourInARowTurnPayload) ProtoMessage()    {}
func (*FourInARowTurnPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_83b407dd639a41e8, []int{4}
}

func (m *FourInARowTurnPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FourInARowTurnPayload.Unmarshal(m, b)
}
func (m *FourInARowTurnPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FourInARowTurnPayload.Marshal(b, m, deterministic)
}
func (m *FourInARowTurnPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FourInARowTurnPayload.Merge(m, src)
}
func (m *FourInARowTurnPayload) XXX_Size() int {
	return xxx_messageInfo_FourInARowTurnPayload.Size(m)
}
func (m *FourInARowTurnPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_FourInARowTurnPayload.DiscardUnknown(m)
}

var xxx_messageInfo_FourInARowTurnPayload proto.InternalMessageInfo

func (m *FourInARowTurnPayload) GetGameID() uint32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

func (m *FourInARowTurnPayload) GetRow() uint32 {
	if m != nil {
		return m.Row
	}
	return 0
}

type ChatMessage struct {
	Context              ChatMessageContext `protobuf:"varint,1,opt,name=context,proto3,enum=ChatMessageContext" json:"context,omitempty"`
	User                 *User              `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Content              string             `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ChatMessage) Reset()         { *m = ChatMessage{} }
func (m *ChatMessage) String() string { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()    {}
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_83b407dd639a41e8, []int{5}
}

func (m *ChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessage.Unmarshal(m, b)
}
func (m *ChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessage.Marshal(b, m, deterministic)
}
func (m *ChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessage.Merge(m, src)
}
func (m *ChatMessage) XXX_Size() int {
	return xxx_messageInfo_ChatMessage.Size(m)
}
func (m *ChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessage proto.InternalMessageInfo

func (m *ChatMessage) GetContext() ChatMessageContext {
	if m != nil {
		return m.Context
	}
	return ChatMessageContext_LOBBY
}

func (m *ChatMessage) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ChatMessage) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type GameEnd struct {
	Result               GameResult `protobuf:"varint,1,opt,name=result,proto3,enum=GameResult" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GameEnd) Reset()         { *m = GameEnd{} }
func (m *GameEnd) String() string { return proto.CompactTextString(m) }
func (*GameEnd) ProtoMessage()    {}
func (*GameEnd) Descriptor() ([]byte, []int) {
	return fileDescriptor_83b407dd639a41e8, []int{6}
}

func (m *GameEnd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameEnd.Unmarshal(m, b)
}
func (m *GameEnd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameEnd.Marshal(b, m, deterministic)
}
func (m *GameEnd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameEnd.Merge(m, src)
}
func (m *GameEnd) XXX_Size() int {
	return xxx_messageInfo_GameEnd.Size(m)
}
func (m *GameEnd) XXX_DiscardUnknown() {
	xxx_messageInfo_GameEnd.DiscardUnknown(m)
}

var xxx_messageInfo_GameEnd proto.InternalMessageInfo

func (m *GameEnd) GetResult() GameResult {
	if m != nil {
		return m.Result
	}
	return GameResult_WON
}

func init() {
	proto.RegisterEnum("GameType", GameType_name, GameType_value)
	proto.RegisterEnum("ChatMessageContext", ChatMessageContext_name, ChatMessageContext_value)
	proto.RegisterEnum("GameResult", GameResult_name, GameResult_value)
	proto.RegisterType((*GameRequest)(nil), "GameRequest")
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*Game)(nil), "Game")
	proto.RegisterType((*GameList)(nil), "GameList")
	proto.RegisterType((*FourInARowTurnPayload)(nil), "FourInARowTurnPayload")
	proto.RegisterType((*ChatMessage)(nil), "ChatMessage")
	proto.RegisterType((*GameEnd)(nil), "GameEnd")
}

func init() { proto.RegisterFile("proto/Types.proto", fileDescriptor_83b407dd639a41e8) }

var fileDescriptor_83b407dd639a41e8 = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0xad, 0xdb, 0xf4, 0x23, 0x37, 0x6a, 0x95, 0x5d, 0x04, 0x0a, 0xa0, 0x49, 0x21, 0x3c, 0x10,
	0x55, 0x10, 0xa4, 0xf2, 0x07, 0xe8, 0x46, 0x37, 0x45, 0xea, 0x1a, 0x64, 0x3a, 0x4d, 0x3c, 0x45,
	0x86, 0x5a, 0x23, 0xd2, 0x6a, 0x67, 0xb6, 0xa3, 0xd1, 0x9f, 0xc1, 0x3f, 0x46, 0x76, 0xda, 0x6d,
	0x12, 0x3c, 0xed, 0xed, 0xfa, 0xdc, 0x73, 0xcf, 0xc9, 0x39, 0x0a, 0x1c, 0xd5, 0x4a, 0x1a, 0xf9,
	0x71, 0xbd, 0xab, 0xb9, 0xce, 0xdc, 0x9c, 0x7c, 0x86, 0xe0, 0x9c, 0x6d, 0x39, 0xe5, 0xb7, 0x0d,
	0xd7, 0x06, 0x11, 0x3c, 0xc1, 0xb6, 0x3c, 0x22, 0x31, 0x49, 0x7d, 0xea, 0x66, 0x3c, 0x06, 0xcf,
	0xec, 0x6a, 0x1e, 0x75, 0x63, 0x92, 0x4e, 0x66, 0x7e, 0x66, 0xf9, 0x56, 0x82, 0x3a, 0x38, 0x79,
	0x05, 0xde, 0xa5, 0xe6, 0xea, 0x7f, 0xa7, 0xc9, 0x1f, 0x02, 0x9e, 0xa5, 0x3f, 0x41, 0x17, 0x27,
	0xd0, 0xad, 0x36, 0x51, 0x2f, 0x26, 0xe9, 0x98, 0x76, 0xab, 0x0d, 0xbe, 0x05, 0xbf, 0x12, 0x95,
	0xa9, 0x98, 0x91, 0x2a, 0xf2, 0x62, 0x92, 0x06, 0xb3, 0x7e, 0x66, 0x9d, 0xe9, 0x03, 0x8e, 0x6f,
	0x60, 0x24, 0xeb, 0x5a, 0x0a, 0x2e, 0x4c, 0xd4, 0x7f, 0xcc, 0xb9, 0x87, 0x93, 0x77, 0x30, 0xb2,
	0x4e, 0xcb, 0x4a, 0x1b, 0x7c, 0x0d, 0xfd, 0x6b, 0xb6, 0xe5, 0x3a, 0x22, 0x71, 0xcf, 0x71, 0x5d,
	0x17, 0x2d, 0x96, 0xcc, 0xe1, 0xf9, 0x99, 0x6c, 0x54, 0x2e, 0xe6, 0x54, 0xde, 0xad, 0x1b, 0x25,
	0xbe, 0xb2, 0xdd, 0x8d, 0x64, 0x1b, 0x7c, 0x01, 0x03, 0xcb, 0xc8, 0xbf, 0xb8, 0x38, 0x63, 0xba,
	0x7f, 0x61, 0x08, 0x3d, 0x25, 0xef, 0x5c, 0x9e, 0x31, 0xb5, 0x63, 0x72, 0x0b, 0xc1, 0xe9, 0x2f,
	0x66, 0x2e, 0xb8, 0xd6, 0xec, 0x9a, 0xe3, 0x07, 0x18, 0xfe, 0x94, 0xc2, 0xf0, 0xdf, 0xc6, 0x5d,
	0x4e, 0x66, 0xcf, 0xb2, 0x47, 0xeb, 0xd3, 0x76, 0x45, 0x0f, 0x1c, 0x7c, 0x09, 0x5e, 0xa3, 0xb9,
	0x72, 0x82, 0xf7, 0x41, 0x1c, 0x84, 0xd1, 0x5e, 0x49, 0x18, 0xd7, 0x90, 0x4f, 0x0f, 0xcf, 0x24,
	0x83, 0xa1, 0x0d, 0xb1, 0x10, 0xb6, 0xb1, 0x81, 0xe2, 0xba, 0xb9, 0x39, 0xb8, 0x05, 0x6d, 0x3c,
	0x07, 0xd1, 0xfd, 0x6a, 0x7a, 0xdc, 0xd6, 0x61, 0x8b, 0xc7, 0x23, 0x18, 0x9f, 0x15, 0x97, 0xb4,
	0xcc, 0x57, 0xe5, 0xbc, 0xa4, 0xc5, 0x55, 0xd8, 0x99, 0xbe, 0x07, 0xfc, 0xf7, 0x13, 0xd1, 0x87,
	0xfe, 0xb2, 0x38, 0x39, 0xf9, 0x1e, 0x76, 0x30, 0x80, 0x61, 0xbe, 0x2a, 0xcf, 0xe7, 0x17, 0x8b,
	0x90, 0x4c, 0x53, 0x80, 0x07, 0x0b, 0x1c, 0x42, 0xef, 0xaa, 0x58, 0x85, 0x1d, 0x1c, 0x81, 0xb7,
	0x2c, 0xbe, 0xad, 0x43, 0x62, 0xa1, 0x75, 0xbe, 0x08, 0xbb, 0x3f, 0x06, 0xee, 0xf7, 0xfb, 0xf4,
	0x37, 0x00, 0x00, 0xff, 0xff, 0x9e, 0xd9, 0xd9, 0x01, 0x93, 0x02, 0x00, 0x00,
}
