# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Types.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/Types.proto", :syntax => :proto3) do
    add_message "GameRequest" do
      optional :name, :string, 1
      optional :type, :enum, 2, "GameType"
    end
    add_message "User" do
      optional :name, :string, 1
    end
    add_message "Game" do
      optional :name, :string, 1
      optional :type, :enum, 2, "GameType"
      optional :id, :uint32, 3
      optional :initiator, :message, 4, "User"
      optional :opponent, :message, 5, "User"
    end
    add_message "GameList" do
      repeated :games, :message, 1, "Game"
    end
    add_message "FourInARowTurnPayload" do
      optional :gameID, :uint32, 1
      optional :row, :uint32, 2
    end
    add_message "ChatMessage" do
      optional :context, :enum, 1, "ChatMessageContext"
      optional :user, :message, 2, "User"
      optional :content, :string, 3
    end
    add_message "GameEnd" do
      optional :result, :enum, 1, "GameResult"
    end
    add_enum "GameType" do
      value :FOUR_IN_A_ROW, 0
    end
    add_enum "ChatMessageContext" do
      value :LOBBY, 0
      value :IN_GAME, 1
    end
    add_enum "GameResult" do
      value :WON, 0
      value :LOST, 1
      value :TIE, 2
    end
  end
end

GameRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameRequest").msgclass
User = Google::Protobuf::DescriptorPool.generated_pool.lookup("User").msgclass
Game = Google::Protobuf::DescriptorPool.generated_pool.lookup("Game").msgclass
GameList = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameList").msgclass
FourInARowTurnPayload = Google::Protobuf::DescriptorPool.generated_pool.lookup("FourInARowTurnPayload").msgclass
ChatMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("ChatMessage").msgclass
GameEnd = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameEnd").msgclass
GameType = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameType").enummodule
ChatMessageContext = Google::Protobuf::DescriptorPool.generated_pool.lookup("ChatMessageContext").enummodule
GameResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameResult").enummodule
